### PR TITLE
Update Turkish language

### PR DESCRIPTION
**Pull request by razor84**
Hi,

Merge please

Thanks.

### CODE REVIEW

**Comment by razor84** [comment]
Hi @SKULSHADY 
This is not merged. Is there an error in the translation or file?

**Comment by SKULSHADY** [comment]
I picked it manually in my private repo yesterday so it's already there.

**Comment by SKULSHADY** [comment]
https://github.com/Havoc-OS/android_frameworks_base/commit/a958d29cf6ce61ad7099816917d05bdb2cff9093

**Comment by razor84** [comment]
I asked this file my friend

core/res/res/values-tr/havoc_strings.xml 

https://github.com/razor84/android_frameworks_base-4/commit/f9aaaee9572a825069d592746103a97142c05147

**Comment by SKULSHADY** [comment]
Oh. I missed that. Can u please make a new one?

**Comment by razor84** [comment]
I added again

https://github.com/Havoc-OS/android_frameworks_base/pull/59

**Pull request closed without merging**
