### PR TITLE
Update and typo fixed

### PR DESCRIPTION
**Pull request by razor84**
Hi

Merge please

Thanks

### CODE REVIEW

**Comment by razor84** [comment]
Hi @SKULSHADY 

This is not merge.

Changes made important

**Comment by SKULSHADY** [comment]
Q clock has been changed so these translations aren't useful anymore

**Comment by razor84** [comment]
I understand. So what do we have to do with Q clock translation?

**Comment by SKULSHADY** [comment]
Nothing for now until I push the new commits

**Comment by razor84** [comment]
OK. Thanks

**Pull request closed without merging**
